""""""""""""
" ~/.vimrc "
""""""""""""

if &compatible
    set nocompatible
endif

set runtimepath^=$HOME/.vim
set runtimepath^=$HOME/.vim/after
set runtimepath^=/usr/share/vim/vimfiles/eclim


" Plug

call plug#begin('~/.vim/plugged')

if has('python') || has('python3')
    Plug 'SirVer/ultisnips'
    Plug 'honza/vim-snippets'
    Plug 'Valloric/YouCompleteMe'
    Plug 'OmniSharp/omnisharp-vim'
endif

Plug 'tpope/vim-dispatch'
Plug 'OrangeT/vim-csharp'
Plug 'bling/vim-bufferline'
Plug 'vim-ctrlspace/vim-ctrlspace'
Plug 'morhetz/gruvbox'
Plug 'baskerville/vim-sxhkdrc'
Plug 'octol/vim-cpp-enhanced-highlight'
Plug 'scrooloose/nerdtree'
Plug 'scrooloose/syntastic'
Plug 'morhetz/gruvbox'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'jeffkreeftmeijer/vim-numbertoggle'
Plug 'ervandew/supertab'
Plug 'bronson/vim-trailing-whitespace'
Plug 'scrooloose/nerdcommenter'
Plug 'chriskempson/base16-vim'
Plug 'tpope/vim-fugitive'
Plug 'tpope/vim-surround'
Plug 'octol/vim-cpp-enhanced-highlight'
Plug 'Shougo/vimshell', { 'rev': '3787e5' }
Plug 'kien/ctrlp.vim'
Plug 'majutsushi/tagbar'
Plug 'suan/vim-instant-markdown'
Plug 'nelstrom/vim-markdown-folding'
Plug 'jeetsukumaran/vim-buffergator'
Plug 'paranoida/vim-airlineish'
Plug 'chrisbra/Colorizer'
Plug 'ap/vim-css-color'
Plug 'KabbAmine/vCoolor.vim'
Plug 'MattesGroeger/vim-bookmarks'
Plug 'amix/vim-zenroom2'
Plug 'junegunn/goyo.vim'
Plug 'jaagr/vim-brogrammer-theme'
Plug 'dracula/vim'
Plug 'joshdick/onedark.vim'
Plug 'joshdick/airline-onedark.vim'
Plug 'ConradIrwin/vim-bracketed-paste'
Plug 'chrisbra/unicode.vim'
Plug 'xuhdev/vim-latex-live-preview'
Plug 'xolox/vim-easytags'
Plug 'xolox/vim-misc'
call plug#end()

" Source configurations
for g:rc in split(glob('$HOME/.vim/vimrc.d/*.vim'), '\n')
	exe 'source' rc
endfor
